import type { Customer, Product, Transaction } from "./types"

export const mockCustomers: Customer[] = [
  {
    id: "C001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@email.com",
    phone: "+91-98765-43210",
    address: "12/5 T Nagar, Chennai, Tamil Nadu 600017",
    joinDate: "2026-01-12",
    totalPurchases: 45,
    totalSpent: 195280.67,
  },
  {
    id: "C002",
    name: "Fatima Bi",
    email: "fatima.bi@email.com",
    phone: "+91-98765-43211",
    address: "45 Triplicane High Road, Chennai, Tamil Nadu 600005",
    joinDate: "2026-01-18",
    totalPurchases: 32,
    totalSpent: 151920.45,
  },
  {
    id: "C003",
    name: "David Raj",
    email: "david.raj@email.com",
    phone: "+91-98765-43212",
    address: "78 Anna Salai, Chennai, Tamil Nadu 600002",
    joinDate: "2026-02-05",
    totalPurchases: 28,
    totalSpent: 130657.89,
  },
  {
    id: "C004",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+91-98765-43213",
    address: "23 Velachery Main Road, Chennai, Tamil Nadu 600042",
    joinDate: "2026-01-25",
    totalPurchases: 52,
    totalSpent: 260034.0,
  },
  {
    id: "C005",
    name: "Mohammed Rafi",
    email: "mohammed.rafi@email.com",
    phone: "+91-98765-43214",
    address: "67 Royapettah High Road, Chennai, Tamil Nadu 600014",
    joinDate: "2026-02-14",
    totalPurchases: 19,
    totalSpent: 82315.65,
  },
  {
    id: "C006",
    name: "Mary Joseph",
    email: "mary.joseph@email.com",
    phone: "+91-98765-43215",
    address: "89 Mylapore Tank Road, Chennai, Tamil Nadu 600004",
    joinDate: "2026-01-08",
    totalPurchases: 38,
    totalSpent: 178450.3,
  },
  {
    id: "C007",
    name: "Amit Patel",
    email: "amit.patel@email.com",
    phone: "+91-98765-43216",
    address: "34 Adyar Gate Road, Chennai, Tamil Nadu 600020",
    joinDate: "2026-02-22",
    totalPurchases: 41,
    totalSpent: 198760.8,
  },
  {
    id: "C008",
    name: "Abubacker",
    email: "abu567@email.com",
    phone: "+91-98765-43217",
    address: "56 Perambur High Road, Chennai, Tamil Nadu 600011",
    joinDate: "2026-01-15",
    totalPurchases: 55,
    totalSpent: 285640.5,
  },
  {
    id: "C009",
    name: "Thomas Daniel",
    email: "thomas.daniel@email.com",
    phone: "+91-98765-43218",
    address: "91 Kodambakkam High Road, Chennai, Tamil Nadu 600024",
    joinDate: "2026-03-05",
    totalPurchases: 25,
    totalSpent: 142890.25,
  },
  {
    id: "C010",
    name: "Lakshmi Iyer",
    email: "lakshmi.iyer@email.com",
    phone: "+91-98765-43219",
    address: "12 Ashok Nagar, Chennai, Tamil Nadu 600083",
    joinDate: "2026-02-18",
    totalPurchases: 33,
    totalSpent: 165432.9,
  },
  {
    id: "C011",
    name: "Abdul Rahman",
    email: "abdul.rahman@email.com",
    phone: "+91-98765-43220",
    address: "88 Thousand Lights, Chennai, Tamil Nadu 600006",
    joinDate: "2026-03-10",
    totalPurchases: 29,
    totalSpent: 148975.4,
  },
  {
    id: "C012",
    name: "Sarah Matthew",
    email: "sarah.matthew@email.com",
    phone: "+91-98765-43221",
    address: "43 Nungambakkam High Road, Chennai, Tamil Nadu 600034",
    joinDate: "2026-01-22",
    totalPurchases: 47,
    totalSpent: 225680.75,
  },
  {
    id: "C013",
    name: "Suresh Reddy",
    email: "suresh.reddy@email.com",
    phone: "+91-98765-43222",
    address: "76 Guindy Industrial Estate, Chennai, Tamil Nadu 600032",
    joinDate: "2026-03-12",
    totalPurchases: 22,
    totalSpent: 118540.6,
  },
  {
    id: "C014",
    name: "Shafi",
    email: "shafi46@email.com",
    phone: "+91-98765-43223",
    address: "29 Egmore High Road, Chennai, Tamil Nadu 600008",
    joinDate: "2026-02-10",
    totalPurchases: 36,
    totalSpent: 172345.85,
  },
  {
    id: "C015",
    name: "John Paul",
    email: "john.paul@email.com",
    phone: "+91-98765-43224",
    address: "55 Kilpauk Garden Road, Chennai, Tamil Nadu 600010",
    joinDate: "2026-03-08",
    totalPurchases: 44,
    totalSpent: 210567.95,
  },
]

export const mockProducts: Product[] = [
  {
    id: "P001",
    name: "Organic Bananas",
    category: "Fruits",
    price: 50.0,
    stock: 250,
    unit: "kg",
    supplier: "Fresh Farms Co.",
    description: "Fresh organic bananas from local farms",
  },
  {
    id: "P002",
    name: "Full Cream Milk",
    category: "Dairy",
    price: 65.0,
    stock: 180,
    unit: "litre",
    supplier: "Dairy Best",
    description: "Grade A full cream milk, pasteurized",
  },
  {
    id: "P003",
    name: "Whole Wheat Bread",
    category: "Bakery",
    price: 45.0,
    stock: 95,
    unit: "loaf",
    supplier: "Artisan Bakery",
    description: "Freshly baked whole wheat bread",
  },
  {
    id: "P004",
    name: "Free-Range Eggs",
    category: "Dairy",
    price: 120.0,
    stock: 120,
    unit: "dozen",
    supplier: "Happy Hens Farm",
    description: "Large free-range eggs, grade AA",
  },
  {
    id: "P005",
    name: "Tomatoes",
    category: "Vegetables",
    price: 40.0,
    stock: 200,
    unit: "kg",
    supplier: "Garden Fresh",
    description: "Vine-ripened tomatoes",
  },
  {
    id: "P006",
    name: "Chicken Breast",
    category: "Meat",
    price: 280.0,
    stock: 85,
    unit: "kg",
    supplier: "Premium Meats",
    description: "Fresh boneless chicken breast",
  },
  {
    id: "P007",
    name: "Orange Juice",
    category: "Beverages",
    price: 150.0,
    stock: 150,
    unit: "litre",
    supplier: "Citrus Grove",
    description: "100% fresh squeezed orange juice",
  },
  {
    id: "P008",
    name: "Spinach",
    category: "Vegetables",
    price: 30.0,
    stock: 110,
    unit: "bunch",
    supplier: "Green Leaf Farms",
    description: "Fresh baby spinach",
  },
  {
    id: "P009",
    name: "Basmati Rice",
    category: "Grains",
    price: 85.0,
    stock: 300,
    unit: "kg",
    supplier: "Golden Harvest",
    description: "Premium aged basmati rice",
  },
  {
    id: "P010",
    name: "Atta (Wheat Flour)",
    category: "Grains",
    price: 45.0,
    stock: 250,
    unit: "kg",
    supplier: "Grain Mills",
    description: "Stone ground whole wheat flour",
  },
  {
    id: "P011",
    name: "Paneer",
    category: "Dairy",
    price: 320.0,
    stock: 75,
    unit: "kg",
    supplier: "Dairy Best",
    description: "Fresh cottage cheese",
  },
  {
    id: "P012",
    name: "Mangoes (Alphonso)",
    category: "Fruits",
    price: 180.0,
    stock: 120,
    unit: "kg",
    supplier: "Tropical Fruits",
    description: "Premium Alphonso mangoes",
  },
  {
    id: "P013",
    name: "Yogurt (Dahi)",
    category: "Dairy",
    price: 55.0,
    stock: 140,
    unit: "kg",
    supplier: "Dairy Best",
    description: "Fresh homestyle yogurt",
  },
  {
    id: "P014",
    name: "Onions",
    category: "Vegetables",
    price: 35.0,
    stock: 280,
    unit: "kg",
    supplier: "Garden Fresh",
    description: "Red onions, locally sourced",
  },
  {
    id: "P015",
    name: "Potatoes",
    category: "Vegetables",
    price: 25.0,
    stock: 320,
    unit: "kg",
    supplier: "Garden Fresh",
    description: "Fresh potatoes",
  },
  {
    id: "P016",
    name: "Green Chillies",
    category: "Vegetables",
    price: 60.0,
    stock: 90,
    unit: "kg",
    supplier: "Spice Farms",
    description: "Fresh green chillies",
  },
  {
    id: "P017",
    name: "Dates (Khajoor)",
    category: "Fruits",
    price: 450.0,
    stock: 65,
    unit: "kg",
    supplier: "Desert Delights",
    description: "Premium Medjool dates",
  },
  {
    id: "P018",
    name: "Coconut Oil",
    category: "Oils",
    price: 250.0,
    stock: 100,
    unit: "litre",
    supplier: "Tropical Oils",
    description: "Cold pressed virgin coconut oil",
  },
  {
    id: "P019",
    name: "Ghee (Clarified Butter)",
    category: "Dairy",
    price: 580.0,
    stock: 80,
    unit: "kg",
    supplier: "Dairy Best",
    description: "Pure cow ghee",
  },
  {
    id: "P020",
    name: "Mutton",
    category: "Meat",
    price: 650.0,
    stock: 55,
    unit: "kg",
    supplier: "Premium Meats",
    description: "Fresh mutton, halal certified",
  },
  {
    id: "P021",
    name: "Lentils (Dal)",
    category: "Grains",
    price: 95.0,
    stock: 200,
    unit: "kg",
    supplier: "Golden Harvest",
    description: "Premium red lentils",
  },
  {
    id: "P022",
    name: "Tea Leaves",
    category: "Beverages",
    price: 180.0,
    stock: 120,
    unit: "kg",
    supplier: "Assam Gardens",
    description: "Premium Assam tea leaves",
  },
  {
    id: "P023",
    name: "Coffee Powder",
    category: "Beverages",
    price: 420.0,
    stock: 85,
    unit: "kg",
    supplier: "Coffee Estates",
    description: "Filter coffee powder, Arabica blend",
  },
  {
    id: "P024",
    name: "Jaggery (Gur)",
    category: "Sweeteners",
    price: 70.0,
    stock: 160,
    unit: "kg",
    supplier: "Organic Sugars",
    description: "Organic jaggery powder",
  },
  {
    id: "P025",
    name: "Turmeric Powder",
    category: "Spices",
    price: 280.0,
    stock: 95,
    unit: "kg",
    supplier: "Spice Farms",
    description: "Pure turmeric powder",
  },
  {
    id: "P026",
    name: "Garam Masala",
    category: "Spices",
    price: 350.0,
    stock: 70,
    unit: "kg",
    supplier: "Spice Farms",
    description: "Premium garam masala blend",
  },
  {
    id: "P027",
    name: "Chickpeas (Chana)",
    category: "Grains",
    price: 75.0,
    stock: 180,
    unit: "kg",
    supplier: "Golden Harvest",
    description: "Kabuli chana, premium quality",
  },
  {
    id: "P028",
    name: "Mustard Oil",
    category: "Oils",
    price: 190.0,
    stock: 130,
    unit: "litre",
    supplier: "Tropical Oils",
    description: "Cold pressed mustard oil",
  },
  {
    id: "P029",
    name: "Apples",
    category: "Fruits",
    price: 140.0,
    stock: 150,
    unit: "kg",
    supplier: "Fresh Farms Co.",
    description: "Kashmiri apples, premium quality",
  },
  {
    id: "P030",
    name: "Curd Rice Mix",
    category: "Snacks",
    price: 65.0,
    stock: 110,
    unit: "kg",
    supplier: "Snack Factory",
    description: "Ready-to-cook curd rice mix",
  },
  {
    id: "P031",
    name: "Pickles (Achar)",
    category: "Condiments",
    price: 220.0,
    stock: 95,
    unit: "kg",
    supplier: "Homemade Delights",
    description: "Mixed vegetable pickle, traditional recipe",
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "T001",
    customerId: "C001",
    customerName: "Rajesh Kumar",
    date: "2026-01-15T10:30:00",
    items: [
      {
        productId: "P001",
        productName: "Organic Bananas",
        quantity: 3,
        price: 50.0,
        subtotal: 150.0,
      },
      {
        productId: "P002",
        productName: "Full Cream Milk",
        quantity: 2,
        price: 65.0,
        subtotal: 130.0,
      },
      {
        productId: "P004",
        productName: "Free-Range Eggs",
        quantity: 1,
        price: 120.0,
        subtotal: 120.0,
      },
    ],
    totalAmount: 400.0,
    paymentMethod: "card",
    status: "completed",
  },
  {
    id: "T002",
    customerId: "C002",
    customerName: "Fatima Bi",
    date: "2026-01-22T11:15:00",
    items: [
      {
        productId: "P003",
        productName: "Whole Wheat Bread",
        quantity: 2,
        price: 45.0,
        subtotal: 90.0,
      },
      {
        productId: "P007",
        productName: "Orange Juice",
        quantity: 1,
        price: 150.0,
        subtotal: 150.0,
      },
    ],
    totalAmount: 240.0,
    paymentMethod: "cash",
    status: "completed",
  },
  {
    id: "T003",
    customerId: "C004",
    customerName: "Priya Sharma",
    date: "2026-02-03T09:45:00",
    items: [
      {
        productId: "P006",
        productName: "Chicken Breast",
        quantity: 2,
        price: 280.0,
        subtotal: 560.0,
      },
      {
        productId: "P005",
        productName: "Tomatoes",
        quantity: 1,
        price: 40.0,
        subtotal: 40.0,
      },
      {
        productId: "P008",
        productName: "Spinach",
        quantity: 2,
        price: 30.0,
        subtotal: 60.0,
      },
    ],
    totalAmount: 660.0,
    paymentMethod: "card",
    status: "completed",
  },
  {
    id: "T004",
    customerId: "C003",
    customerName: "David Raj",
    date: "2026-02-12T14:20:00",
    items: [
      {
        productId: "P009",
        productName: "Basmati Rice",
        quantity: 5,
        price: 85.0,
        subtotal: 425.0,
      },
      {
        productId: "P001",
        productName: "Organic Bananas",
        quantity: 2,
        price: 50.0,
        subtotal: 100.0,
      },
    ],
    totalAmount: 525.0,
    paymentMethod: "mobile",
    status: "completed",
  },
  {
    id: "T005",
    customerId: "C005",
    customerName: "Mohammed Rafi",
    date: "2026-02-20T16:00:00",
    items: [
      {
        productId: "P011",
        productName: "Paneer",
        quantity: 1,
        price: 320.0,
        subtotal: 320.0,
      },
      {
        productId: "P004",
        productName: "Free-Range Eggs",
        quantity: 2,
        price: 120.0,
        subtotal: 240.0,
      },
      {
        productId: "P013",
        productName: "Yogurt (Dahi)",
        quantity: 1,
        price: 55.0,
        subtotal: 55.0,
      },
    ],
    totalAmount: 615.0,
    paymentMethod: "card",
    status: "completed",
  },
  {
    id: "T006",
    customerId: "C007",
    customerName: "Amit Patel",
    date: "2026-03-05T10:30:00",
    items: [
      {
        productId: "P017",
        productName: "Dates (Khajoor)",
        quantity: 1,
        price: 450.0,
        subtotal: 450.0,
      },
      {
        productId: "P020",
        productName: "Mutton",
        quantity: 2,
        price: 650.0,
        subtotal: 1300.0,
      },
    ],
    totalAmount: 1750.0,
    paymentMethod: "card",
    status: "completed",
  },
]
